main: net.tfminecraft.MarketBlock
api-version: 1.20
name: MarketBlock
version: ${project.version}
author: Drefvelin

depend: [DenarEconomy, TLibs]
softdepend: [Cooking]

commands:
  marketblock:
    useage: /<command>
    description: MarketBlock Command