main: net.tfminecraft.marketblock.MarketBlock
api-version: '1.21.10'
name: MarketBlock
version: ${project.version}
author: Drefvelin

depend: [DenarEconomy, TLibs]
softdepend: [Cooking]

commands:
  marketblock:
    useage: /<command>
    description: MarketBlock Command